---
- name: Configure simple policy on FortiGate firewall
  hosts: firewalls
  connection: httpapi
  gather_facts: false
  collections:
    - fortinet.fortios

  vars:
    vdom: "root"
    firewall_policy:
      name: "Allow_HTTP_LAN_to_WAN"
      policyid: 10
      srcintf: "port1"
      dstintf: "port2"
      srcaddr: "all"
      dstaddr: "all"
      action: "accept"
      schedule: "always"
      service: "HTTP"
      nat: "enable"

  tasks:
    - name: Create or update firewall policy
      fortios_firewall_policy:
        vdom: "{{ vdom }}"
        state: "present"
        firewall_policy:
          policyid: "{{ firewall_policy.policyid }}"
          name: "{{ firewall_policy.name }}"
          srcintf:
            - name: "{{ firewall_policy.srcintf }}"
          dstintf:
            - name: "{{ firewall_policy.dstintf }}"
          srcaddr:
            - name: "{{ firewall_policy.srcaddr }}"
          dstaddr:
            - name: "{{ firewall_policy.dstaddr }}"
          action: "{{ firewall_policy.action }}"
          schedule: "{{ firewall_policy.schedule }}"
          service:
            - name: "{{ firewall_policy.service }}"
          nat: "{{ firewall_policy.nat }}"
